-- ============================================================
-- TESLA CONTROL ESCOLAR - FASE 8
-- Tiempo real + PDA/DNI + salidas + tardanza automática
-- Ejecutar una sola vez en Supabase SQL Editor.
-- ============================================================

-- 1) Datos necesarios para el modo PDA.
alter table public.students
  add column if not exists dni text,
  add column if not exists access_authorized boolean not null default true,
  add column if not exists access_note text;

create unique index if not exists idx_students_dni_unique
  on public.students(dni)
  where dni is not null and btrim(dni) <> '';

-- 2) Entrada/salida sobre la asistencia diaria existente.
alter table public.attendance
  add column if not exists exit_time time,
  add column if not exists entry_recorded_at timestamptz,
  add column if not exists exit_recorded_at timestamptz,
  add column if not exists entry_source text,
  add column if not exists exit_source text;

-- Restringimos los nuevos valores sin romper registros anteriores nulos.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'attendance_entry_source_check'
  ) then
    alter table public.attendance add constraint attendance_entry_source_check
      check (entry_source is null or entry_source in ('WEB','PDA','MANUAL'));
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'attendance_exit_source_check'
  ) then
    alter table public.attendance add constraint attendance_exit_source_check
      check (exit_source is null or exit_source in ('WEB','PDA','MANUAL'));
  end if;
end $$;

-- 3) Historial de movimientos de acceso.
create table if not exists public.access_events (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  event_type text not null check (event_type in ('ENTRY','EXIT')),
  source text not null default 'WEB' check (source in ('WEB','PDA','MANUAL')),
  device_label text,
  event_date date not null default current_date,
  event_time time not null default localtime,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_access_events_student_date
  on public.access_events(student_id, event_date);
create index if not exists idx_access_events_date_time
  on public.access_events(event_date, event_time desc);

alter table public.access_events enable row level security;

drop policy if exists "Authenticated users read access events" on public.access_events;
create policy "Authenticated users read access events"
  on public.access_events for select to authenticated using (true);

drop policy if exists "Authenticated users create access events" on public.access_events;
create policy "Authenticated users create access events"
  on public.access_events for insert to authenticated with check (true);

-- 4) Configuración para crear notificación silenciosa de tardanza.
alter table public.school_settings
  add column if not exists late_notification_enabled boolean not null default true;

update public.school_settings
set late_notification_enabled = true
where late_notification_enabled is null;

-- Crea la notificación en BD para cualquier entrada tardía (web, PDA u offline sincronizado).
create or replace function public.ensure_late_notification_from_attendance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_enabled boolean := true;
  v_next integer;
begin
  if new.status <> 'LATE' then
    return new;
  end if;

  select coalesce(late_notification_enabled, true)
  into v_enabled
  from public.school_settings
  order by id
  limit 1;

  if coalesce(v_enabled, true) = false then
    return new;
  end if;

  if exists (
    select 1 from public.notifications n where n.attendance_id = new.id
  ) then
    return new;
  end if;

  select coalesce(max(notification_number), 0) + 1
  into v_next
  from public.notifications
  where student_id = new.student_id;

  insert into public.notifications (
    student_id,
    presentation_control_id,
    attendance_id,
    notification_number,
    notification_type,
    observation,
    date
  ) values (
    new.student_id,
    null,
    new.id,
    v_next,
    'LATE_ENTRY',
    'Tardanza en el ingreso. Hora registrada: ' || to_char(new.entry_time, 'HH24:MI') || '.',
    new.date
  )
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists trg_auto_late_notification on public.attendance;
create trigger trg_auto_late_notification
after insert or update of status, entry_time on public.attendance
for each row
when (new.status = 'LATE')
execute function public.ensure_late_notification_from_attendance();

-- 5) Auditoría de access_events si Fase 6 ya creó log_audit_event().
do $$
begin
  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.proname='log_audit_event'
  ) then
    execute 'drop trigger if exists trg_audit_access_events on public.access_events';
    execute 'create trigger trg_audit_access_events after insert or update or delete on public.access_events for each row execute function public.log_audit_event()';
  end if;
end $$;

-- 6) Supabase Realtime. Solo añade las tablas que todavía no estén publicadas.
do $$
declare
  t text;
begin
  foreach t in array array[
    'attendance',
    'presentation_controls',
    'presentation_violations',
    'notifications',
    'alerts',
    'students',
    'classrooms',
    'access_events'
  ] loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- 7) Para updates/deletes más completos por Realtime.
alter table public.attendance replica identity full;
alter table public.presentation_controls replica identity full;
alter table public.notifications replica identity full;
alter table public.access_events replica identity full;

-- Verificación rápida.
select
  (select count(*) from pg_publication_tables where pubname='supabase_realtime' and schemaname='public') as realtime_tables,
  (select data_type from information_schema.columns where table_schema='public' and table_name='students' and column_name='dni') as dni_type,
  (select data_type from information_schema.columns where table_schema='public' and table_name='attendance' and column_name='exit_time') as exit_time_type;
